// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: beerpb/beer.proto

package beerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BeerService_CreateBeer_FullMethodName = "/beerpb.BeerService/CreateBeer"
	BeerService_GetBeer_FullMethodName    = "/beerpb.BeerService/GetBeer"
	BeerService_ListBeers_FullMethodName  = "/beerpb.BeerService/ListBeers"
	BeerService_DeleteBeer_FullMethodName = "/beerpb.BeerService/DeleteBeer"
)

// BeerServiceClient is the client API for BeerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BeerServiceClient interface {
	CreateBeer(ctx context.Context, in *CreateBeerRequest, opts ...grpc.CallOption) (*BeerResponse, error)
	GetBeer(ctx context.Context, in *GetBeerRequest, opts ...grpc.CallOption) (*BeerResponse, error)
	ListBeers(ctx context.Context, in *ListBeersRequest, opts ...grpc.CallOption) (*ListBeersResponse, error)
	DeleteBeer(ctx context.Context, in *DeleteBeerRequest, opts ...grpc.CallOption) (*BeerResponse, error)
}

type beerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBeerServiceClient(cc grpc.ClientConnInterface) BeerServiceClient {
	return &beerServiceClient{cc}
}

func (c *beerServiceClient) CreateBeer(ctx context.Context, in *CreateBeerRequest, opts ...grpc.CallOption) (*BeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeerResponse)
	err := c.cc.Invoke(ctx, BeerService_CreateBeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beerServiceClient) GetBeer(ctx context.Context, in *GetBeerRequest, opts ...grpc.CallOption) (*BeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeerResponse)
	err := c.cc.Invoke(ctx, BeerService_GetBeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beerServiceClient) ListBeers(ctx context.Context, in *ListBeersRequest, opts ...grpc.CallOption) (*ListBeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBeersResponse)
	err := c.cc.Invoke(ctx, BeerService_ListBeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beerServiceClient) DeleteBeer(ctx context.Context, in *DeleteBeerRequest, opts ...grpc.CallOption) (*BeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeerResponse)
	err := c.cc.Invoke(ctx, BeerService_DeleteBeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeerServiceServer is the server API for BeerService service.
// All implementations must embed UnimplementedBeerServiceServer
// for forward compatibility.
type BeerServiceServer interface {
	CreateBeer(context.Context, *CreateBeerRequest) (*BeerResponse, error)
	GetBeer(context.Context, *GetBeerRequest) (*BeerResponse, error)
	ListBeers(context.Context, *ListBeersRequest) (*ListBeersResponse, error)
	DeleteBeer(context.Context, *DeleteBeerRequest) (*BeerResponse, error)
	mustEmbedUnimplementedBeerServiceServer()
}

// UnimplementedBeerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBeerServiceServer struct{}

func (UnimplementedBeerServiceServer) CreateBeer(context.Context, *CreateBeerRequest) (*BeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBeer not implemented")
}
func (UnimplementedBeerServiceServer) GetBeer(context.Context, *GetBeerRequest) (*BeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBeer not implemented")
}
func (UnimplementedBeerServiceServer) ListBeers(context.Context, *ListBeersRequest) (*ListBeersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBeers not implemented")
}
func (UnimplementedBeerServiceServer) DeleteBeer(context.Context, *DeleteBeerRequest) (*BeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBeer not implemented")
}
func (UnimplementedBeerServiceServer) mustEmbedUnimplementedBeerServiceServer() {}
func (UnimplementedBeerServiceServer) testEmbeddedByValue()                     {}

// UnsafeBeerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BeerServiceServer will
// result in compilation errors.
type UnsafeBeerServiceServer interface {
	mustEmbedUnimplementedBeerServiceServer()
}

func RegisterBeerServiceServer(s grpc.ServiceRegistrar, srv BeerServiceServer) {
	// If the following call pancis, it indicates UnimplementedBeerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BeerService_ServiceDesc, srv)
}

func _BeerService_CreateBeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeerServiceServer).CreateBeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeerService_CreateBeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeerServiceServer).CreateBeer(ctx, req.(*CreateBeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeerService_GetBeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeerServiceServer).GetBeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeerService_GetBeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeerServiceServer).GetBeer(ctx, req.(*GetBeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeerService_ListBeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeerServiceServer).ListBeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeerService_ListBeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeerServiceServer).ListBeers(ctx, req.(*ListBeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeerService_DeleteBeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeerServiceServer).DeleteBeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeerService_DeleteBeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeerServiceServer).DeleteBeer(ctx, req.(*DeleteBeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BeerService_ServiceDesc is the grpc.ServiceDesc for BeerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BeerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beerpb.BeerService",
	HandlerType: (*BeerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBeer",
			Handler:    _BeerService_CreateBeer_Handler,
		},
		{
			MethodName: "GetBeer",
			Handler:    _BeerService_GetBeer_Handler,
		},
		{
			MethodName: "ListBeers",
			Handler:    _BeerService_ListBeers_Handler,
		},
		{
			MethodName: "DeleteBeer",
			Handler:    _BeerService_DeleteBeer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "beerpb/beer.proto",
}
