// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: beerpb/beer.proto

package beerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Beer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Style         string                 `protobuf:"bytes,3,opt,name=style,proto3" json:"style,omitempty"`
	Abv           float64                `protobuf:"fixed64,4,opt,name=abv,proto3" json:"abv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Beer) Reset() {
	*x = Beer{}
	mi := &file_beerpb_beer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Beer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Beer) ProtoMessage() {}

func (x *Beer) ProtoReflect() protoreflect.Message {
	mi := &file_beerpb_beer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Beer.ProtoReflect.Descriptor instead.
func (*Beer) Descriptor() ([]byte, []int) {
	return file_beerpb_beer_proto_rawDescGZIP(), []int{0}
}

func (x *Beer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Beer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Beer) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *Beer) GetAbv() float64 {
	if x != nil {
		return x.Abv
	}
	return 0
}

type CreateBeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Beer          *Beer                  `protobuf:"bytes,1,opt,name=beer,proto3" json:"beer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBeerRequest) Reset() {
	*x = CreateBeerRequest{}
	mi := &file_beerpb_beer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBeerRequest) ProtoMessage() {}

func (x *CreateBeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beerpb_beer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBeerRequest.ProtoReflect.Descriptor instead.
func (*CreateBeerRequest) Descriptor() ([]byte, []int) {
	return file_beerpb_beer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBeerRequest) GetBeer() *Beer {
	if x != nil {
		return x.Beer
	}
	return nil
}

type GetBeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeerRequest) Reset() {
	*x = GetBeerRequest{}
	mi := &file_beerpb_beer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeerRequest) ProtoMessage() {}

func (x *GetBeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beerpb_beer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeerRequest.ProtoReflect.Descriptor instead.
func (*GetBeerRequest) Descriptor() ([]byte, []int) {
	return file_beerpb_beer_proto_rawDescGZIP(), []int{2}
}

func (x *GetBeerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBeerRequest) Reset() {
	*x = DeleteBeerRequest{}
	mi := &file_beerpb_beer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBeerRequest) ProtoMessage() {}

func (x *DeleteBeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beerpb_beer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBeerRequest.ProtoReflect.Descriptor instead.
func (*DeleteBeerRequest) Descriptor() ([]byte, []int) {
	return file_beerpb_beer_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteBeerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Beer          *Beer                  `protobuf:"bytes,1,opt,name=beer,proto3" json:"beer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeerResponse) Reset() {
	*x = BeerResponse{}
	mi := &file_beerpb_beer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeerResponse) ProtoMessage() {}

func (x *BeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beerpb_beer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeerResponse.ProtoReflect.Descriptor instead.
func (*BeerResponse) Descriptor() ([]byte, []int) {
	return file_beerpb_beer_proto_rawDescGZIP(), []int{4}
}

func (x *BeerResponse) GetBeer() *Beer {
	if x != nil {
		return x.Beer
	}
	return nil
}

type ListBeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBeersRequest) Reset() {
	*x = ListBeersRequest{}
	mi := &file_beerpb_beer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeersRequest) ProtoMessage() {}

func (x *ListBeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beerpb_beer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeersRequest.ProtoReflect.Descriptor instead.
func (*ListBeersRequest) Descriptor() ([]byte, []int) {
	return file_beerpb_beer_proto_rawDescGZIP(), []int{5}
}

type ListBeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Beers         []*Beer                `protobuf:"bytes,1,rep,name=beers,proto3" json:"beers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBeersResponse) Reset() {
	*x = ListBeersResponse{}
	mi := &file_beerpb_beer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeersResponse) ProtoMessage() {}

func (x *ListBeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beerpb_beer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeersResponse.ProtoReflect.Descriptor instead.
func (*ListBeersResponse) Descriptor() ([]byte, []int) {
	return file_beerpb_beer_proto_rawDescGZIP(), []int{6}
}

func (x *ListBeersResponse) GetBeers() []*Beer {
	if x != nil {
		return x.Beers
	}
	return nil
}

var File_beerpb_beer_proto protoreflect.FileDescriptor

const file_beerpb_beer_proto_rawDesc = "" +
	"\n" +
	"\x11beerpb/beer.proto\x12\x06beerpb\"R\n" +
	"\x04Beer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05style\x18\x03 \x01(\tR\x05style\x12\x10\n" +
	"\x03abv\x18\x04 \x01(\x01R\x03abv\"5\n" +
	"\x11CreateBeerRequest\x12 \n" +
	"\x04beer\x18\x01 \x01(\v2\f.beerpb.BeerR\x04beer\" \n" +
	"\x0eGetBeerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11DeleteBeerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\fBeerResponse\x12 \n" +
	"\x04beer\x18\x01 \x01(\v2\f.beerpb.BeerR\x04beer\"\x12\n" +
	"\x10ListBeersRequest\"7\n" +
	"\x11ListBeersResponse\x12\"\n" +
	"\x05beers\x18\x01 \x03(\v2\f.beerpb.BeerR\x05beers2\x86\x02\n" +
	"\vBeerService\x12=\n" +
	"\n" +
	"CreateBeer\x12\x19.beerpb.CreateBeerRequest\x1a\x14.beerpb.BeerResponse\x127\n" +
	"\aGetBeer\x12\x16.beerpb.GetBeerRequest\x1a\x14.beerpb.BeerResponse\x12@\n" +
	"\tListBeers\x12\x18.beerpb.ListBeersRequest\x1a\x19.beerpb.ListBeersResponse\x12=\n" +
	"\n" +
	"DeleteBeer\x12\x19.beerpb.DeleteBeerRequest\x1a\x14.beerpb.BeerResponseB/Z-example.com/hounddog-test-go-app/proto/beerpbb\x06proto3"

var (
	file_beerpb_beer_proto_rawDescOnce sync.Once
	file_beerpb_beer_proto_rawDescData []byte
)

func file_beerpb_beer_proto_rawDescGZIP() []byte {
	file_beerpb_beer_proto_rawDescOnce.Do(func() {
		file_beerpb_beer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beerpb_beer_proto_rawDesc), len(file_beerpb_beer_proto_rawDesc)))
	})
	return file_beerpb_beer_proto_rawDescData
}

var file_beerpb_beer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_beerpb_beer_proto_goTypes = []any{
	(*Beer)(nil),              // 0: beerpb.Beer
	(*CreateBeerRequest)(nil), // 1: beerpb.CreateBeerRequest
	(*GetBeerRequest)(nil),    // 2: beerpb.GetBeerRequest
	(*DeleteBeerRequest)(nil), // 3: beerpb.DeleteBeerRequest
	(*BeerResponse)(nil),      // 4: beerpb.BeerResponse
	(*ListBeersRequest)(nil),  // 5: beerpb.ListBeersRequest
	(*ListBeersResponse)(nil), // 6: beerpb.ListBeersResponse
}
var file_beerpb_beer_proto_depIdxs = []int32{
	0, // 0: beerpb.CreateBeerRequest.beer:type_name -> beerpb.Beer
	0, // 1: beerpb.BeerResponse.beer:type_name -> beerpb.Beer
	0, // 2: beerpb.ListBeersResponse.beers:type_name -> beerpb.Beer
	1, // 3: beerpb.BeerService.CreateBeer:input_type -> beerpb.CreateBeerRequest
	2, // 4: beerpb.BeerService.GetBeer:input_type -> beerpb.GetBeerRequest
	5, // 5: beerpb.BeerService.ListBeers:input_type -> beerpb.ListBeersRequest
	3, // 6: beerpb.BeerService.DeleteBeer:input_type -> beerpb.DeleteBeerRequest
	4, // 7: beerpb.BeerService.CreateBeer:output_type -> beerpb.BeerResponse
	4, // 8: beerpb.BeerService.GetBeer:output_type -> beerpb.BeerResponse
	6, // 9: beerpb.BeerService.ListBeers:output_type -> beerpb.ListBeersResponse
	4, // 10: beerpb.BeerService.DeleteBeer:output_type -> beerpb.BeerResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_beerpb_beer_proto_init() }
func file_beerpb_beer_proto_init() {
	if File_beerpb_beer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beerpb_beer_proto_rawDesc), len(file_beerpb_beer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beerpb_beer_proto_goTypes,
		DependencyIndexes: file_beerpb_beer_proto_depIdxs,
		MessageInfos:      file_beerpb_beer_proto_msgTypes,
	}.Build()
	File_beerpb_beer_proto = out.File
	file_beerpb_beer_proto_goTypes = nil
	file_beerpb_beer_proto_depIdxs = nil
}
